version: '3.8'

services:
  backend:
    build:
      context: rentals-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: rentals-web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

